from ormar import Text, Integer, Float

from Server.Models.BaseModel import BaseModel


class Contracts(BaseModel):
    Serial = Text(primary_key=True)
    NameEntity = Text()
    NitEntity = Integer()
    EntityCode = Integer()
    Department = Text()
    City = Text()
    Location = Text()
    Order = Text()
    Sector = Text()
    Branch = Text()
    CentralEntity = Text()
    ProcessPurchase = Text()
    SerialContract = Text()
    ReferenceContract = Text()
    StateContract = Text()
    CodeCategoryMain = Text()
    DescriptionProcess = Text()
    TypeContract = Text()
    ContractingMode = Text()
    JustifyContractingMode = Text()
    DateSign = Text()
    DateStartContract = Text()
    DateEndContract = Text()
    DateStartExecution = Text()
    DateEndExecution = Text()
    DeliveryConditions = Text()
    ProviderTypeDocument = Text()
    ProviderDocument = Text()
    ProviderAwarder = Text()
    IsGroup = Text()
    IsPyme = Text()
    EnableAdvancePayment = Text()
    Liquidation = Text()
    EnvironmentalObligation = Text()
    PostConsumerObligation = Text()
    Reversal = Text()
    ValueContract = Integer()
    ValueEnableAdvancePayment = Integer()
    ValueInvoice = Integer()
    ValuePendingPayment = Integer()
    ValuePaid = Integer()
    ValueAmortized = Integer()
    ValuePendingAmortized = Integer()
    ValuePendingExecution = Integer()
    StateBankOfNationalInvestmentProjects = Text()
    CodeBankOfNationalInvestmentProjects = Text()
    YearBankOfNationalInvestmentProjects = Text()
    BalanceCertificateOfBudgetaryAvailability = Float()
    BalanceVigence = Integer()
    IsPostConflict = Text()
    ProcessUrl = Text()
    ExpenseDestination = Text()
    OrigenResources = Text()
    DaysAdded = Integer()
    PointsOfTheAgreement = Text()
    PillarsOfTheAgreement = Text()
    LegalRepresentativeName = Text()
    LegalRepresentativeNationality = Text()
    LegalRepresentativeTypeIdentification = Text()
    LegalRepresentativeGender = Text()
    GeneralBudgetOfNation = Integer()
    GeneralParticipationSystem = Integer()
    GeneralRoyaltiesSystem = Integer()
    ResourcesOfAnotherEntities = Integer()
    CreditResources = Integer()
    OwnResources = Integer()
    LastUpdate = Text()
    DateStartLiquidation = Text()
    DateEndLiquidation = Text()
    CodeProvider = Text()
    ObjectContract = Text()

    class Meta:
        tablename = 'Contracts'
