export interface Contract {
  Serial: string
  NameEntity: string
  NitEntity: number
  EntityCode: number
  Department: string
  City: string
  Location: string
  Order: string
  Sector: string
  Branch: string
  CentralEntity: string
  ProcessPurchase: string
  SerialContract: string
  ReferenceContract: string
  StateContract: string
  CodeCategoryMain: string
  DescriptionProcess: string
  TypeContract: string
  ContractingMode: string
  JustifyContractingMode: string
  DateSign?: string
  DateStartContract?: string
  DateEndContract?: string
  DateStartExecution?: string
  DateEndExecution?: string
  DeliveryConditions: string
  ProviderTypeDocument: string
  ProviderDocument: string
  ProviderAwarder: string
  IsGroup: string
  IsPyme: string
  EnableAdvancePayment: string
  Liquidation: string
  EnvironmentalObligation: string
  PostConsumerObligation: string
  Reversal: string
  ValueContract: number
  ValueEnableAdvancePayment: number
  ValueInvoice: number
  ValuePendingPayment: number
  ValuePaid: number
  ValueAmortized: number
  ValuePendingAmortized: number
  ValuePendingExecution: number
  StateBankOfNationalInvestmentProjects: string
  CodeBankOfNationalInvestmentProjects: string
  YearBankOfNationalInvestmentProjects: string
  BalanceCertificateOfBudgetaryAvailability: number
  BalanceVigence: number
  IsPostConflict: string
  ProcessUrl: string
  ExpenseDestination: string
  OrigenResources: string
  DaysAdded: number
  PointsOfTheAgreement: string
  PillarsOfTheAgreement: string
  LegalRepresentativeName: string
  LegalRepresentativeNationality: string
  LegalRepresentativeTypeIdentification: string
  LegalRepresentativeGender: string
  GeneralBudgetOfNation: number
  GeneralParticipationSystem: number
  GeneralRoyaltiesSystem: number
  ResourcesOfAnotherEntities: number
  CreditResources: number
  OwnResources: number
  LastUpdate: string
  DateStartLiquidation?: string
  DateEndLiquidation?: string
  CodeProvider: string
  ObjectContract?: string
}
