import {inject, Injectable} from "@angular/core";
import {HttpClient} from "@angular/common/http";
import {of} from "rxjs";

@Injectable({
  providedIn: 'root'
})
export class AppService {
  private readonly httpService = inject(HttpClient)

  public getContracts() {
    return of([
      {
        "Serial": "CO1.PCCNTR.1000001-DTAM NACION-CS No. 020-2019",
        "NameEntity": "PARQUES NACIONALES NATURALES DE COLOMBIA  DIRECCION  TERRITORIAL AMAZONIA",
        "NitEntity": 900005502,
        "EntityCode": 701224107,
        "Department": "Distrito Capital de Bogotá",
        "City": "No Definido",
        "Location": "Colombia, Bogotá, Bogotá",
        "Order": "Territorial",
        "Sector": "Ambiente y Desarrollo Sostenible",
        "Branch": "Ejecutivo",
        "CentralEntity": "Centralizada",
        "ProcessPurchase": "CO1.BDOS.848814",
        "SerialContract": "CO1.PCCNTR.1000001",
        "ReferenceContract": "DTAM NACION-CS No. 020-2019",
        "StateContract": "Cerrado",
        "CodeCategoryMain": "V1.47131500",
        "DescriptionProcess": "Contratar a monto agotable por el sistema de precios unitarios sin formula de reajuste el suministro de elementos de aseo y limpieza e insumos de cafetería y restaurante para los Parques Nacionales Naturales de  Amacayacu Cahuinarí Río Puré y Yaigojé Apaporis",
        "TypeContract": "Suministros",
        "ContractingMode": "Mínima cuantía",
        "JustifyContractingMode": "Presupuesto inferior al 10% de la menor cuantía",
        "DateSign": "06/19/2019",
        "DateStartContract": "06/18/2019",
        "DateEndContract": "12/31/2019",
        "DateStartExecution": "06/18/2019",
        "DateEndExecution": "12/31/2019",
        "DeliveryConditions": "Como acordado previamente",
        "ProviderTypeDocument": "No Definido",
        "ProviderDocument": "830130048",
        "ProviderAwarder": "INDUSTRIAS GUERRERO Y COMPAÑIA SAS",
        "IsGroup": "No",
        "IsPyme": "Si",
        "EnableAdvancePayment": "No",
        "Liquidation": "Si",
        "EnvironmentalObligation": "No",
        "PostConsumerObligation": "No",
        "Reversal": "No",
        "ValueContract": 17897916,
        "ValueEnableAdvancePayment": 0,
        "ValueInvoice": 17896237,
        "ValuePendingPayment": 1679,
        "ValuePaid": 17896237,
        "ValueAmortized": 0,
        "ValuePendingAmortized": 0,
        "ValuePendingExecution": 11812624,
        "StateBankOfNationalInvestmentProjects": "Válido",
        "CodeBankOfNationalInvestmentProjects": "No Definido",
        "YearBankOfNationalInvestmentProjects": "N/D",
        "BalanceCertificateOfBudgetaryAvailability": 17897916,
        "BalanceVigence": 0,
        "IsPostConflict": "No",
        "ProcessUrl": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.846428&isFromPublicArea=True&isModal=true&asPopupView=true",
        "ExpenseDestination": "Funcionamiento",
        "OrigenResources": "Distribuido",
        "DaysAdded": 0,
        "PointsOfTheAgreement": "No aplica",
        "PillarsOfTheAgreement": "No aplica",
        "LegalRepresentativeName": "ROSA DORIS PINZON HERNANDEZ",
        "LegalRepresentativeNationality": "COLOMBIAA",
        "LegalRepresentativeTypeIdentification": "Sin Descripcion",
        "LegalRepresentativeGender": "No Definido",
        "GeneralBudgetOfNation": 0,
        "GeneralParticipationSystem": 0,
        "GeneralRoyaltiesSystem": 0,
        "ResourcesOfAnotherEntities": 0,
        "CreditResources": 0,
        "OwnResources": 0,
        "LastUpdate": "12/30/2020 12:00:00 AM",
        "DateStartLiquidation": "2019-06-18 22:00:00",
        "DateEndLiquidation": "2021-01-03 22:00:00",
        "CodeProvider": "700658065",
        "ObjectContract": "Contratar a monto agotable por el sistema de precios unitarios sin formula de reajuste el suministro de elementos de aseo y limpieza e insumos de cafetería y restaurante para los Parques Nacionales Naturales de  Amacayacu Cahuinarí Río Puré y Yaigojé Apaporis"
      },
      {
        "Serial": "CO1.PCCNTR.1000002-CO1.PCCNTR.1000002",
        "NameEntity": "ESTABLECIMIENTO CARCELARIO PURIFICACION",
        "NitEntity": 809003243,
        "EntityCode": 702957242,
        "Department": "Tolima",
        "City": "Purificación",
        "Location": "Colombia,  Tolima ,  Purificación",
        "Order": "Nacional",
        "Sector": "Ley de Justicia",
        "Branch": "Judicial",
        "CentralEntity": "Descentralizada",
        "ProcessPurchase": "CO1.BDOS.855601",
        "SerialContract": "CO1.PCCNTR.1000002",
        "ReferenceContract": "CO1.PCCNTR.1000002",
        "StateContract": "Borrador",
        "CodeCategoryMain": "V1.76101503",
        "DescriptionProcess": "PARA CONTRATAR EL SERVICIO DE FUMIGACION DESRATIZACION Y CONTROL DE CALIDAD DEL AGUA EN LAS AREAS COMUNES DEL ESTABLECIMIENTO DEL ESTABLECIMIENTO PENITENCIARIO DE MEDIANA SEGURIDAD Y CARCELARIO DE PURIFICACIÓN TOLIMA",
        "TypeContract": "Suministros",
        "ContractingMode": "Mínima cuantía",
        "JustifyContractingMode": "Presupuesto inferior al 10% de la menor cuantía",
        "DateSign": null,
        "DateStartContract": null,
        "DateEndContract": null,
        "DateStartExecution": null,
        "DateEndExecution": null,
        "DeliveryConditions": "No Definido",
        "ProviderTypeDocument": "Cédula de Ciudadanía",
        "ProviderDocument": "39708149",
        "ProviderAwarder": "OLGA YANET ROJAS BARBOSA",
        "IsGroup": "No",
        "IsPyme": "No",
        "EnableAdvancePayment": "No Definido",
        "Liquidation": "No",
        "EnvironmentalObligation": "No",
        "PostConsumerObligation": "No",
        "Reversal": "No",
        "ValueContract": 1200000,
        "ValueEnableAdvancePayment": 0,
        "ValueInvoice": 0,
        "ValuePendingPayment": 1200000,
        "ValuePaid": 0,
        "ValueAmortized": 0,
        "ValuePendingAmortized": 0,
        "ValuePendingExecution": 1200000,
        "StateBankOfNationalInvestmentProjects": "Válido",
        "CodeBankOfNationalInvestmentProjects": "No Definido",
        "YearBankOfNationalInvestmentProjects": "N/D",
        "BalanceCertificateOfBudgetaryAvailability": 1200000,
        "BalanceVigence": 0,
        "IsPostConflict": "No",
        "ProcessUrl": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.848603&isFromPublicArea=True&isModal=true&asPopupView=true",
        "ExpenseDestination": "Funcionamiento",
        "OrigenResources": "Distribuido",
        "DaysAdded": 0,
        "PointsOfTheAgreement": "No aplica",
        "PillarsOfTheAgreement": "No aplica",
        "LegalRepresentativeName": "OLGA YANET ROJAS BARBOSA",
        "LegalRepresentativeNationality": "COLOMBIANA",
        "LegalRepresentativeTypeIdentification": "Sin Descripcion",
        "LegalRepresentativeGender": "No Definido",
        "GeneralBudgetOfNation": 0,
        "GeneralParticipationSystem": 0,
        "GeneralRoyaltiesSystem": 0,
        "ResourcesOfAnotherEntities": 0,
        "CreditResources": 0,
        "OwnResources": 0,
        "LastUpdate": "06/18/2019 12:00:00 AM",
        "DateStartLiquidation": null,
        "DateEndLiquidation": null,
        "CodeProvider": "704055086",
        "ObjectContract": null
      },
      {
        "Serial": "CO1.PCCNTR.100001-CO1.PCCNTR.100001",
        "NameEntity": "AGENCIA NACIONAL DE DEFENSA JURÍDICA DEL ESTADO",
        "NitEntity": 900507741,
        "EntityCode": 700660053,
        "Department": "Distrito Capital de Bogotá",
        "City": "No Definido",
        "Location": "Colombia, Bogotá, Bogotá",
        "Order": "Nacional",
        "Sector": "Ley de Justicia",
        "Branch": "Ejecutivo",
        "CentralEntity": "Descentralizada",
        "ProcessPurchase": "CO1.BDOS.115112",
        "SerialContract": "CO1.PCCNTR.100001",
        "ReferenceContract": "CO1.PCCNTR.100001",
        "StateContract": "Activo",
        "CodeCategoryMain": "V1.80111609",
        "DescriptionProcess": "Prestar servicios de apoyo técnico y operativo al Grupo Interno de Trabajo de Asesoría Territorial Recuperación de Recursos y de Acción de Repetición  GRAT en la alimentación y seguimiento de las bases de datos así como en la organización y programación de reuniones eventos y manejo de información a",
        "TypeContract": "Prestación de servicios",
        "ContractingMode": "Contratación Directa (con ofertas)",
        "JustifyContractingMode": "Ejecución de trabajos artísticos",
        "DateSign": "09/13/2017",
        "DateStartContract": "01/04/2017",
        "DateEndContract": "12/31/2017",
        "DateStartExecution": "01/04/2017",
        "DateEndExecution": "12/31/2017",
        "DeliveryConditions": "No Definido",
        "ProviderTypeDocument": "Cédula de Ciudadanía",
        "ProviderDocument": "1110544590",
        "ProviderAwarder": "Jessica Lizeth Martínez Gaviria",
        "IsGroup": "No",
        "IsPyme": "No",
        "EnableAdvancePayment": "No",
        "Liquidation": "No",
        "EnvironmentalObligation": "No",
        "PostConsumerObligation": "No",
        "Reversal": "No",
        "ValueContract": 28568400,
        "ValueEnableAdvancePayment": 0,
        "ValueInvoice": 21386400,
        "ValuePendingPayment": 7182000,
        "ValuePaid": 21386400,
        "ValueAmortized": 0,
        "ValuePendingAmortized": 0,
        "ValuePendingExecution": 28568400,
        "StateBankOfNationalInvestmentProjects": "Válido",
        "CodeBankOfNationalInvestmentProjects": "No Definido",
        "YearBankOfNationalInvestmentProjects": "N/D",
        "BalanceCertificateOfBudgetaryAvailability": 28568400,
        "BalanceVigence": 0,
        "IsPostConflict": "No",
        "ProcessUrl": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.113538&isFromPublicArea=True&isModal=true&asPopupView=true",
        "ExpenseDestination": "Funcionamiento",
        "OrigenResources": "Distribuido",
        "DaysAdded": 0,
        "PointsOfTheAgreement": "No aplica",
        "PillarsOfTheAgreement": "No aplica",
        "LegalRepresentativeName": "Jessica Lizeth Martinez Gaviria",
        "LegalRepresentativeNationality": "Colombiana",
        "LegalRepresentativeTypeIdentification": "Sin Descripcion",
        "LegalRepresentativeGender": "No Definido",
        "GeneralBudgetOfNation": 0,
        "GeneralParticipationSystem": 0,
        "GeneralRoyaltiesSystem": 0,
        "ResourcesOfAnotherEntities": 0,
        "CreditResources": 0,
        "OwnResources": 0,
        "LastUpdate": "08/01/2019 12:00:00 AM",
        "DateStartLiquidation": null,
        "DateEndLiquidation": null,
        "CodeProvider": "701404204",
        "ObjectContract": "Prestar servicios de apoyo técnico y operativo al Grupo Interno de Trabajo de Asesoría Territorial Recuperación de Recursos y de Acción de Repetición  GRAT en la alimentación y seguimiento de las bases de datos así como en la organización y programación de reuniones eventos y manejo de información a través de la página web de la Entidad"
      },
      {
        "Serial": "CO1.PCCNTR.100002-CO1.PCCNTR.100002",
        "NameEntity": "AGENCIA NACIONAL DE DEFENSA JURÍDICA DEL ESTADO",
        "NitEntity": 900507741,
        "EntityCode": 700660053,
        "Department": "Distrito Capital de Bogotá",
        "City": "No Definido",
        "Location": "Colombia, Bogotá, Bogotá",
        "Order": "Nacional",
        "Sector": "Ley de Justicia",
        "Branch": "Ejecutivo",
        "CentralEntity": "Descentralizada",
        "ProcessPurchase": "CO1.BDOS.115113",
        "SerialContract": "CO1.PCCNTR.100002",
        "ReferenceContract": "CO1.PCCNTR.100002",
        "StateContract": "cedido",
        "CodeCategoryMain": "V1.80111607",
        "DescriptionProcess": "Prestar los servicios de apoyo a la Dirección de Defensa Jurídica para la vigilancia y revisión de los procesos judiciales y arbitrales en los que la ANDJE ha intervenido procesalmente o en los que deba hacer seguimiento de acuerdo con las decisiones adoptadas en la Instancia de Selección creada med",
        "TypeContract": "Prestación de servicios",
        "ContractingMode": "Contratación Directa (con ofertas)",
        "JustifyContractingMode": "Ejecución de trabajos artísticos",
        "DateSign": "08/25/2017",
        "DateStartContract": "01/04/2017",
        "DateEndContract": "12/31/2017",
        "DateStartExecution": "01/04/2017",
        "DateEndExecution": "12/31/2017",
        "DeliveryConditions": "No Definido",
        "ProviderTypeDocument": "Cédula de Ciudadanía",
        "ProviderDocument": "80745366",
        "ProviderAwarder": "JONATHAN ALBER RONDON BARBOSA",
        "IsGroup": "No",
        "IsPyme": "No",
        "EnableAdvancePayment": "No",
        "Liquidation": "No",
        "EnvironmentalObligation": "No",
        "PostConsumerObligation": "No",
        "Reversal": "No",
        "ValueContract": 27745000,
        "ValueEnableAdvancePayment": 0,
        "ValueInvoice": 27745000,
        "ValuePendingPayment": 0,
        "ValuePaid": 27745000,
        "ValueAmortized": 0,
        "ValuePendingAmortized": 0,
        "ValuePendingExecution": 27745000,
        "StateBankOfNationalInvestmentProjects": "Válido",
        "CodeBankOfNationalInvestmentProjects": "No Definido",
        "YearBankOfNationalInvestmentProjects": "N/D",
        "BalanceCertificateOfBudgetaryAvailability": 27745000,
        "BalanceVigence": 0,
        "IsPostConflict": "No",
        "ProcessUrl": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.113726&isFromPublicArea=True&isModal=true&asPopupView=true",
        "ExpenseDestination": "Funcionamiento",
        "OrigenResources": "Distribuido",
        "DaysAdded": 0,
        "PointsOfTheAgreement": "No aplica",
        "PillarsOfTheAgreement": "No aplica",
        "LegalRepresentativeName": "JONATHAN ALBER RONDON BARBOSA",
        "LegalRepresentativeNationality": "COLOMBIANO",
        "LegalRepresentativeTypeIdentification": "Sin Descripcion",
        "LegalRepresentativeGender": "No Definido",
        "GeneralBudgetOfNation": 0,
        "GeneralParticipationSystem": 0,
        "GeneralRoyaltiesSystem": 0,
        "ResourcesOfAnotherEntities": 0,
        "CreditResources": 0,
        "OwnResources": 0,
        "LastUpdate": "08/01/2019 12:00:00 AM",
        "DateStartLiquidation": null,
        "DateEndLiquidation": null,
        "CodeProvider": "702505447",
        "ObjectContract": "Prestar los servicios de apoyo a la Dirección de Defensa Jurídica para la vigilancia y revisión de los procesos judiciales y arbitrales en los que la ANDJE ha intervenido procesalmente o en los que deba hacer seguimiento de acuerdo con las decisiones adoptadas en la Instancia de Selección creada mediante Acuerdo N 1 de 2013 del Consejo Directivo de la ANDJE"
      },
      {
        "Serial": "CO1.PCCNTR.100003-CO1.PCCNTR.100003",
        "NameEntity": "AGENCIA NACIONAL DE DEFENSA JURÍDICA DEL ESTADO",
        "NitEntity": 900507741,
        "EntityCode": 700660053,
        "Department": "Distrito Capital de Bogotá",
        "City": "No Definido",
        "Location": "Colombia, Bogotá, Bogotá",
        "Order": "Nacional",
        "Sector": "Ley de Justicia",
        "Branch": "Ejecutivo",
        "CentralEntity": "Descentralizada",
        "ProcessPurchase": "CO1.BDOS.115022",
        "SerialContract": "CO1.PCCNTR.100003",
        "ReferenceContract": "CO1.PCCNTR.100003",
        "StateContract": "Activo",
        "CodeCategoryMain": "V1.80111609",
        "DescriptionProcess": "Prestar servicios profesionales para apoyar a la Dirección de Gestión de la Información de la Agencia Nacional de Defensa Jurídica del Estado en la depuración procesamiento y validación de la información contenida en el Sistema Único de Gestión e Información Litigiosa del Estado y en las demás activ",
        "TypeContract": "Prestación de servicios",
        "ContractingMode": "Contratación Directa (con ofertas)",
        "JustifyContractingMode": "Ejecución de trabajos artísticos",
        "DateSign": "04/26/2017",
        "DateStartContract": "01/04/2017",
        "DateEndContract": "12/31/2017",
        "DateStartExecution": "01/04/2017",
        "DateEndExecution": "12/31/2017",
        "DeliveryConditions": "No Definido",
        "ProviderTypeDocument": "Cédula de Ciudadanía",
        "ProviderDocument": "1010191965",
        "ProviderAwarder": "Luis Andres Ordoñez Gil",
        "IsGroup": "No",
        "IsPyme": "No",
        "EnableAdvancePayment": "No",
        "Liquidation": "No",
        "EnvironmentalObligation": "No",
        "PostConsumerObligation": "No",
        "Reversal": "No",
        "ValueContract": 45536400,
        "ValueEnableAdvancePayment": 0,
        "ValueInvoice": 45283420,
        "ValuePendingPayment": 252980,
        "ValuePaid": 45283420,
        "ValueAmortized": 0,
        "ValuePendingAmortized": 0,
        "ValuePendingExecution": 45536400,
        "StateBankOfNationalInvestmentProjects": "Válido",
        "CodeBankOfNationalInvestmentProjects": "No Definido",
        "YearBankOfNationalInvestmentProjects": "N/D",
        "BalanceCertificateOfBudgetaryAvailability": 45536400,
        "BalanceVigence": 0,
        "IsPostConflict": "No",
        "ProcessUrl": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.113540&isFromPublicArea=True&isModal=true&asPopupView=true",
        "ExpenseDestination": "Funcionamiento",
        "OrigenResources": "Distribuido",
        "DaysAdded": 0,
        "PointsOfTheAgreement": "No aplica",
        "PillarsOfTheAgreement": "No aplica",
        "LegalRepresentativeName": "Luis Andres Ordoñez Gil",
        "LegalRepresentativeNationality": "Colombiano",
        "LegalRepresentativeTypeIdentification": "Sin Descripcion",
        "LegalRepresentativeGender": "No Definido",
        "GeneralBudgetOfNation": 0,
        "GeneralParticipationSystem": 0,
        "GeneralRoyaltiesSystem": 0,
        "ResourcesOfAnotherEntities": 0,
        "CreditResources": 0,
        "OwnResources": 0,
        "LastUpdate": "08/01/2019 12:00:00 AM",
        "DateStartLiquidation": null,
        "DateEndLiquidation": null,
        "CodeProvider": "701412215",
        "ObjectContract": "Prestar servicios profesionales para apoyar la Dirección de Gestión de Información de la Agencia Nacional Jurídica del Estado en la depuración procesamiento y validación de la información contenida en el Sistema Único de Gestión e Información Litigiosa del Estado  y en las demás actividades que requiera la Dirección de Gestión de Información"
      },
      {
        "Serial": "CO1.PCCNTR.100004-CO1.PCCNTR.100004",
        "NameEntity": "DEPARTAMENTO NACIONAL DE PLANEACIÓN",
        "NitEntity": 899999011,
        "EntityCode": 700220049,
        "Department": "Distrito Capital de Bogotá",
        "City": "Bogotá",
        "Location": "Colombia, Bogotá, Bogotá",
        "Order": "Nacional",
        "Sector": "Planeación",
        "Branch": "Ejecutivo",
        "CentralEntity": "No Definido",
        "ProcessPurchase": "CO1.BDOS.116581",
        "SerialContract": "CO1.PCCNTR.100004",
        "ReferenceContract": "CO1.PCCNTR.100004",
        "StateContract": "Activo",
        "CodeCategoryMain": "V1.80101600",
        "DescriptionProcess": "Apoyar al Departamento Nacional de Planeación  DNP en los procesos de selección y contratación de bienes y servicios de consultoría y no consultoría que deba realizar la entidad para cumplir los compromisos adquiridos con la Banca Multilateral en la ejecución de recursos provenientes de créditos y C",
        "TypeContract": "Prestación de servicios",
        "ContractingMode": "Contratación régimen especial",
        "JustifyContractingMode": "Regla aplicable",
        "DateSign": "01/06/2017",
        "DateStartContract": "01/06/2017",
        "DateEndContract": "12/04/2017",
        "DateStartExecution": "01/06/2017",
        "DateEndExecution": "12/05/2017",
        "DeliveryConditions": "A convenir",
        "ProviderTypeDocument": "Cédula de Ciudadanía",
        "ProviderDocument": "527084138",
        "ProviderAwarder": "PILAR ROCIO VALERO FUENTES",
        "IsGroup": "No",
        "IsPyme": "No",
        "EnableAdvancePayment": "No",
        "Liquidation": "No",
        "EnvironmentalObligation": "No",
        "PostConsumerObligation": "No",
        "Reversal": "No",
        "ValueContract": 143169404,
        "ValueEnableAdvancePayment": 0,
        "ValueInvoice": 0,
        "ValuePendingPayment": 143169404,
        "ValuePaid": 0,
        "ValueAmortized": 0,
        "ValuePendingAmortized": 0,
        "ValuePendingExecution": 143169404,
        "StateBankOfNationalInvestmentProjects": "Válido",
        "CodeBankOfNationalInvestmentProjects": "No Definido",
        "YearBankOfNationalInvestmentProjects": "N/D",
        "BalanceCertificateOfBudgetaryAvailability": 143169404,
        "BalanceVigence": 0,
        "IsPostConflict": "No",
        "ProcessUrl": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.113634&isFromPublicArea=True&isModal=true&asPopupView=true",
        "ExpenseDestination": "Inversión",
        "OrigenResources": "Distribuido",
        "DaysAdded": 0,
        "PointsOfTheAgreement": "No aplica",
        "PillarsOfTheAgreement": "No aplica",
        "LegalRepresentativeName": "PILAR VALERO",
        "LegalRepresentativeNationality": "COLOMBIANA",
        "LegalRepresentativeTypeIdentification": "Sin Descripcion",
        "LegalRepresentativeGender": "No Definido",
        "GeneralBudgetOfNation": 0,
        "GeneralParticipationSystem": 0,
        "GeneralRoyaltiesSystem": 0,
        "ResourcesOfAnotherEntities": 0,
        "CreditResources": 0,
        "OwnResources": 0,
        "LastUpdate": "09/06/2018 12:00:00 AM",
        "DateStartLiquidation": null,
        "DateEndLiquidation": null,
        "CodeProvider": "701286106",
        "ObjectContract": "Apoyar al Departamento Nacional de Planeación  DNP en los procesos de selección y contratación de bienes y servicios de consultoría y no consultoría que deba realizar la entidad para cumplir los compromisos adquiridos con la Banca Multilateral en la ejecución de recursos provenientes de créditos y Cooperaciones Técnicas establecidos en los planes de adquisiciones dentro de los cuales se encuentra el préstamo 3154OCCO Proyecto de Eficiencia al Servicio del Ciudadano"
      },
      {
        "Serial": "CO1.PCCNTR.10001-2-06-25596-0807-2015",
        "NameEntity": "EMPRESA DE ACUEDUCTO Y ALCANTARILLADO DE BOGOTÁ  ESP",
        "NitEntity": 899999094,
        "EntityCode": 700064108,
        "Department": "Distrito Capital de Bogotá",
        "City": "Bogotá",
        "Location": "Colombia, Bogotá, Bogotá",
        "Order": "Territorial",
        "Sector": "Industria",
        "Branch": "Corporación Autónoma",
        "CentralEntity": "No Definido",
        "ProcessPurchase": "CO1.BDOS.28503",
        "SerialContract": "CO1.PCCNTR.10001",
        "ReferenceContract": "2-06-25596-0807-2015",
        "StateContract": "Borrador",
        "CodeCategoryMain": "V1.83101500",
        "DescriptionProcess": "SUMINISTRO DE QUIMICOS PARA EL MANTENIMIENTO INDUSTRIAL DE LA PTAR SALITRE",
        "TypeContract": "Suministros",
        "ContractingMode": "Contratación régimen especial",
        "JustifyContractingMode": "Regla aplicable",
        "DateSign": null,
        "DateStartContract": "12/16/2015",
        "DateEndContract": "04/10/2016",
        "DateStartExecution": null,
        "DateEndExecution": null,
        "DeliveryConditions": "No Definido",
        "ProviderTypeDocument": "No Definido",
        "ProviderDocument": "8301464943",
        "ProviderAwarder": "QSM CHEMICALS AND SERVICES SAS",
        "IsGroup": "No",
        "IsPyme": "No",
        "EnableAdvancePayment": "No",
        "Liquidation": "No",
        "EnvironmentalObligation": "No",
        "PostConsumerObligation": "No",
        "Reversal": "No",
        "ValueContract": 0,
        "ValueEnableAdvancePayment": 0,
        "ValueInvoice": 0,
        "ValuePendingPayment": 0,
        "ValuePaid": 0,
        "ValueAmortized": 0,
        "ValuePendingAmortized": 0,
        "ValuePendingExecution": 0,
        "StateBankOfNationalInvestmentProjects": "Válido",
        "CodeBankOfNationalInvestmentProjects": "No Definido",
        "YearBankOfNationalInvestmentProjects": "N/D",
        "BalanceCertificateOfBudgetaryAvailability": 45779444,
        "BalanceVigence": 0,
        "IsPostConflict": "No",
        "ProcessUrl": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.26801&isFromPublicArea=True&isModal=true&asPopupView=true",
        "ExpenseDestination": "Funcionamiento",
        "OrigenResources": "Distribuido",
        "DaysAdded": 0,
        "PointsOfTheAgreement": "No aplica",
        "PillarsOfTheAgreement": "No aplica",
        "LegalRepresentativeName": "CARLOS HERNÁN MORA MOLANO",
        "LegalRepresentativeNationality": "COLOMBIANO",
        "LegalRepresentativeTypeIdentification": "Sin Descripcion",
        "LegalRepresentativeGender": "No Definido",
        "GeneralBudgetOfNation": 0,
        "GeneralParticipationSystem": 0,
        "GeneralRoyaltiesSystem": 0,
        "ResourcesOfAnotherEntities": 0,
        "CreditResources": 0,
        "OwnResources": 0,
        "LastUpdate": "09/06/2018 12:00:00 AM",
        "DateStartLiquidation": null,
        "DateEndLiquidation": null,
        "CodeProvider": "700474067",
        "ObjectContract": "SUMINISTRO DE QUIMICOS PARA EL MANTENIMIENTO INDUSTRIAL DE LA PTAR SALITRE"
      },
      {
        "Serial": "CO1.PCCNTR.1000201-CONTRATO 121",
        "NameEntity": "ESM BATALLÓN ASPC NO 6",
        "NitEntity": 901541245,
        "EntityCode": 702962226,
        "Department": "Tolima",
        "City": "Ibagué",
        "Location": "Colombia,  Tolima ,  Ibagué",
        "Order": "Nacional",
        "Sector": "Servicio Público",
        "Branch": "Ejecutivo",
        "CentralEntity": "Centralizada",
        "ProcessPurchase": "CO1.BDOS.834401",
        "SerialContract": "CO1.PCCNTR.1000201",
        "ReferenceContract": "CONTRATO 121",
        "StateContract": "enviado Proveedor",
        "CodeCategoryMain": "V1.76111501",
        "DescriptionProcess": "PRESTACION DEL SERVICIO DE ASEO Y DESINFECCION A TODO COSTO PARA LOS ESTABLECIMIENTOS DE SANIDAD MILITAR 51755044 Y 5213",
        "TypeContract": "Prestación de servicios",
        "ContractingMode": "Selección Abreviada de Menor Cuantía",
        "JustifyContractingMode": "Presupuesto menor al 10% de la Menor Cuantía",
        "DateSign": null,
        "DateStartContract": "06/26/2019",
        "DateEndContract": "12/15/2019",
        "DateStartExecution": "06/26/2019",
        "DateEndExecution": "12/15/2019",
        "DeliveryConditions": "A convenir",
        "ProviderTypeDocument": "No Definido",
        "ProviderDocument": "900562598",
        "ProviderAwarder": "KIOS SAS",
        "IsGroup": "No",
        "IsPyme": "Si",
        "EnableAdvancePayment": "No",
        "Liquidation": "No",
        "EnvironmentalObligation": "No",
        "PostConsumerObligation": "No",
        "Reversal": "No",
        "ValueContract": 133000000,
        "ValueEnableAdvancePayment": 0,
        "ValueInvoice": 0,
        "ValuePendingPayment": 133000000,
        "ValuePaid": 0,
        "ValueAmortized": 0,
        "ValuePendingAmortized": 0,
        "ValuePendingExecution": 133000000,
        "StateBankOfNationalInvestmentProjects": "Válido",
        "CodeBankOfNationalInvestmentProjects": "No Definido",
        "YearBankOfNationalInvestmentProjects": "2019",
        "BalanceCertificateOfBudgetaryAvailability": 0,
        "BalanceVigence": 0,
        "IsPostConflict": "No",
        "ProcessUrl": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.844616&isFromPublicArea=True&isModal=true&asPopupView=true",
        "ExpenseDestination": "Funcionamiento",
        "OrigenResources": "Distribuido",
        "DaysAdded": 0,
        "PointsOfTheAgreement": "No aplica",
        "PillarsOfTheAgreement": "No aplica",
        "LegalRepresentativeName": "YOLIMA ANDREA VELASQUEZ",
        "LegalRepresentativeNationality": "COLOMBIA",
        "LegalRepresentativeTypeIdentification": "Sin Descripcion",
        "LegalRepresentativeGender": "No Definido",
        "GeneralBudgetOfNation": 0,
        "GeneralParticipationSystem": 0,
        "GeneralRoyaltiesSystem": 0,
        "ResourcesOfAnotherEntities": 0,
        "CreditResources": 0,
        "OwnResources": 0,
        "LastUpdate": "03/02/2021 12:00:00 AM",
        "DateStartLiquidation": null,
        "DateEndLiquidation": null,
        "CodeProvider": "701231128",
        "ObjectContract": "CONTRATAR LA PRESTACION DEL SERVICIO DE ASEO Y DESINFECCION HOSPITALARIA A TODO COSTO PARA REALIZAR EN LAS INSTALACIONES DE LOS ESTABLECIMIENTOS SANIDAD MILITAR CENTRALIZADOS POR EL CENAC IBAGUE"
      },
      {
        "Serial": "CO1.PCCNTR.1000202-010-2019-EPCTUMACO",
        "NameEntity": "ESTABLECIMIENTO PENITENCIARIO DE MEDIANA SEGURIDAD Y CARCELARIO DE TUMACO",
        "NitEntity": 840000137,
        "EntityCode": 703706218,
        "Department": "Nariño",
        "City": "Tumaco",
        "Location": "Colombia,  Nariño ,  Tumaco",
        "Order": "Territorial",
        "Sector": "Ley de Justicia",
        "Branch": "Ejecutivo",
        "CentralEntity": "Centralizada",
        "ProcessPurchase": "CO1.BDOS.858216",
        "SerialContract": "CO1.PCCNTR.1000202",
        "ReferenceContract": "010-2019-EPCTUMACO",
        "StateContract": "En aprobación",
        "CodeCategoryMain": "V1.50131700",
        "DescriptionProcess": "CONTRATAR EL SUMINISTRO DE BEBIDAS GASEOSAS E HIDRATANTES CON DESTINO AL ALMACEN EXPENDIO DEL ESTABLECIMIENTO PENITENCIARIO DE MEDIANA SEGURIDAD Y CARCELARIO DE TUMACO N",
        "TypeContract": "Suministros",
        "ContractingMode": "Mínima cuantía",
        "JustifyContractingMode": "Presupuesto inferior al 10% de la menor cuantía",
        "DateSign": null,
        "DateStartContract": "06/14/2019",
        "DateEndContract": "06/14/2019",
        "DateStartExecution": "06/14/2019",
        "DateEndExecution": "06/14/2019",
        "DeliveryConditions": "Como acordado previamente",
        "ProviderTypeDocument": "Cédula de Ciudadanía",
        "ProviderDocument": "59827312",
        "ProviderAwarder": "MONTALVO DIAZ DALLYS ANDREA",
        "IsGroup": "No",
        "IsPyme": "Si",
        "EnableAdvancePayment": "No",
        "Liquidation": "No",
        "EnvironmentalObligation": "No",
        "PostConsumerObligation": "No",
        "Reversal": "No",
        "ValueContract": 2404123,
        "ValueEnableAdvancePayment": 0,
        "ValueInvoice": 0,
        "ValuePendingPayment": 2404123,
        "ValuePaid": 0,
        "ValueAmortized": 0,
        "ValuePendingAmortized": 0,
        "ValuePendingExecution": 2404123,
        "StateBankOfNationalInvestmentProjects": "Válido",
        "CodeBankOfNationalInvestmentProjects": "No Definido",
        "YearBankOfNationalInvestmentProjects": "N/D",
        "BalanceCertificateOfBudgetaryAvailability": 0,
        "BalanceVigence": 0,
        "IsPostConflict": "No",
        "ProcessUrl": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.852119&isFromPublicArea=True&isModal=true&asPopupView=true",
        "ExpenseDestination": "Funcionamiento",
        "OrigenResources": "Distribuido",
        "DaysAdded": 0,
        "PointsOfTheAgreement": "No aplica",
        "PillarsOfTheAgreement": "No aplica",
        "LegalRepresentativeName": "MONTALVO DIAZ DALLYS ANDREA",
        "LegalRepresentativeNationality": "COLOMBIANA",
        "LegalRepresentativeTypeIdentification": "Sin Descripcion",
        "LegalRepresentativeGender": "No Definido",
        "GeneralBudgetOfNation": 0,
        "GeneralParticipationSystem": 0,
        "GeneralRoyaltiesSystem": 0,
        "ResourcesOfAnotherEntities": 0,
        "CreditResources": 0,
        "OwnResources": 0,
        "LastUpdate": "06/26/2019 12:00:00 AM",
        "DateStartLiquidation": null,
        "DateEndLiquidation": null,
        "CodeProvider": "704085075",
        "ObjectContract": "CONTRATAR EL SUMINISTRO DE BEBIDAS GASEOSAS E HIDRATANTES CON DESTINO AL ALMACEN EXPENDIO DEL ESTABLECIMIENTO PENITENCIARIO DE MEDIANA SEGURIDAD Y CARCELARIO DE TUMACO N"
      },
      {
        "Serial": "CO1.PCCNTR.1000301-009-2019-EPCTUMACO",
        "NameEntity": "ESTABLECIMIENTO PENITENCIARIO DE MEDIANA SEGURIDAD Y CARCELARIO DE TUMACO",
        "NitEntity": 840000137,
        "EntityCode": 703706218,
        "Department": "Nariño",
        "City": "Tumaco",
        "Location": "Colombia,  Nariño ,  Tumaco",
        "Order": "Territorial",
        "Sector": "Ley de Justicia",
        "Branch": "Ejecutivo",
        "CentralEntity": "Centralizada",
        "ProcessPurchase": "CO1.BDOS.856604",
        "SerialContract": "CO1.PCCNTR.1000301",
        "ReferenceContract": "009-2019-EPCTUMACO",
        "StateContract": "En aprobación",
        "CodeCategoryMain": "V1.50131700",
        "DescriptionProcess": "CONTRATAR EL SUMINISTRO DE PRODUCTOS ALIMENTICIOS CON DESTINO AL ALMACÉN EXPENDIO DEL ESTABLECIMIENTO PENITENCIARIO DE MEDIANA SEGURIDAD Y CARCELARIO DE TUMACO N",
        "TypeContract": "Suministros",
        "ContractingMode": "Mínima cuantía",
        "JustifyContractingMode": "Presupuesto inferior al 10% de la menor cuantía",
        "DateSign": null,
        "DateStartContract": "06/13/2019",
        "DateEndContract": "07/13/2019",
        "DateStartExecution": "06/13/2019",
        "DateEndExecution": "07/13/2019",
        "DeliveryConditions": "Como acordado previamente",
        "ProviderTypeDocument": "Cédula de Ciudadanía",
        "ProviderDocument": "1085285773",
        "ProviderAwarder": "EDISNAR",
        "IsGroup": "No",
        "IsPyme": "Si",
        "EnableAdvancePayment": "No",
        "Liquidation": "No",
        "EnvironmentalObligation": "No",
        "PostConsumerObligation": "No",
        "Reversal": "No",
        "ValueContract": 4369500,
        "ValueEnableAdvancePayment": 0,
        "ValueInvoice": 0,
        "ValuePendingPayment": 4369500,
        "ValuePaid": 0,
        "ValueAmortized": 0,
        "ValuePendingAmortized": 0,
        "ValuePendingExecution": 4369500,
        "StateBankOfNationalInvestmentProjects": "Válido",
        "CodeBankOfNationalInvestmentProjects": "No Definido",
        "YearBankOfNationalInvestmentProjects": "N/D",
        "BalanceCertificateOfBudgetaryAvailability": 0,
        "BalanceVigence": 0,
        "IsPostConflict": "No",
        "ProcessUrl": "https://community.secop.gov.co/Public/Tendering/OpportunityDetail/Index?noticeUID=CO1.NTC.850905&isFromPublicArea=True&isModal=true&asPopupView=true",
        "ExpenseDestination": "Funcionamiento",
        "OrigenResources": "Distribuido",
        "DaysAdded": 0,
        "PointsOfTheAgreement": "No aplica",
        "PillarsOfTheAgreement": "No aplica",
        "LegalRepresentativeName": "Leny Maribel Bastidas Morán",
        "LegalRepresentativeNationality": "Colombiana",
        "LegalRepresentativeTypeIdentification": "Sin Descripcion",
        "LegalRepresentativeGender": "No Definido",
        "GeneralBudgetOfNation": 0,
        "GeneralParticipationSystem": 0,
        "GeneralRoyaltiesSystem": 0,
        "ResourcesOfAnotherEntities": 0,
        "CreditResources": 0,
        "OwnResources": 0,
        "LastUpdate": "06/16/2019 12:00:00 AM",
        "DateStartLiquidation": null,
        "DateEndLiquidation": null,
        "CodeProvider": "704023076",
        "ObjectContract": "CONTRATAR EL SUMINISTRO DE PRODUCTOS ALIMENTICIOS CON DESTINO AL ALMACEN EXPENDIO DEL ESTABLECIMIENTO PENITENCIARIO DE MEDIANA SEGURIDAD Y CARCELARIO DE TUMACO N"
      }
    ])
  }
}

